{"name": "Site with more than one photo", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5606d6d0295e <unknown>\n#1 0x5606d67b7b76 <unknown>\n#2 0x5606d680545e <unknown>\n#3 0x5606d6805731 <unknown>\n#4 0x5606d68494f4 <unknown>\n#5 0x5606d682920d <unknown>\n#6 0x5606d684718a <unknown>\n#7 0x5606d6828f83 <unknown>\n#8 0x5606d67f901e <unknown>\n#9 0x5606d67f9cfe <unknown>\n#10 0x5606d6cd79f1 <unknown>\n#11 0x5606d6cdabee <unknown>\n#12 0x5606d6cda66b <unknown>\n#13 0x5606d6cdb015 <unknown>\n#14 0x5606d6cc9402 <unknown>\n#15 0x5606d6cdb39d <unknown>\n#16 0x5606d6cb35c5 <unknown>\n#17 0x5606d6cf3018 <unknown>\n#18 0x5606d6cf322f <unknown>\n#19 0x5606d6d0154c <unknown>\n#20 0x7f4c8b694ac3 <unknown>", "trace": "self = <Tests.test_Sites.TestSites object at 0x7f8f6d181b90>\ndriver = <selenium.webdriver.edge.webdriver.WebDriver (session=\"b28ad1746ec0403ed41eecca32c2cce4\")>\n\n    @severity(severity_level.CRITICAL)\n    @allure.feature('Individual Sites')\n    @allure.title(\"Site with more than one photo\")\n    @allure.issue(\"QP-264\", \"Story QP-264\")\n    @allure.issue(\"QP-356\", \"Epic QP-356\")\n    @allure.testcase(\"58413\", \"C58413\")\n    def test_20(self, driver):\n        sites_obj = Sites(driver)\n        main_nav_obj = MainNavigation(driver)\n        about_obj = AboutPage(driver)\n        if len(list(self.several_images_site.keys())) == 0:\n            pytest.skip(\"No sites available with several images\")\n        site_id = list(self.several_images_site.keys())[0]\n>       if sites_obj.is_sites_page_title_visible(self.sites_page_content[\"heading_title\"]):\n\nTests/test_Sites.py:485: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPages/SitesPage.py:66: in is_sites_page_title_visible\n    page_title = wait.until(EC.visibility_of_element_located((By.XPATH, f\"//h1[.='{title}']\")))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"b28ad1746ec0403ed41eecca32c2cce4\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x7f8f6d8e1c60>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x5606d6d0295e <unknown>\nE       #1 0x5606d67b7b76 <unknown>\nE       #2 0x5606d680545e <unknown>\nE       #3 0x5606d6805731 <unknown>\nE       #4 0x5606d68494f4 <unknown>\nE       #5 0x5606d682920d <unknown>\nE       #6 0x5606d684718a <unknown>\nE       #7 0x5606d6828f83 <unknown>\nE       #8 0x5606d67f901e <unknown>\nE       #9 0x5606d67f9cfe <unknown>\nE       #10 0x5606d6cd79f1 <unknown>\nE       #11 0x5606d6cdabee <unknown>\nE       #12 0x5606d6cda66b <unknown>\nE       #13 0x5606d6cdb015 <unknown>\nE       #14 0x5606d6cc9402 <unknown>\nE       #15 0x5606d6cdb39d <unknown>\nE       #16 0x5606d6cb35c5 <unknown>\nE       #17 0x5606d6cf3018 <unknown>\nE       #18 0x5606d6cf322f <unknown>\nE       #19 0x5606d6d0154c <unknown>\nE       #20 0x7f4c8b694ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException"}, "parameters": [{"name": "driver", "value": "'edge'"}], "start": 1732957600438, "stop": 1732957632032, "uuid": "428a4db4-158d-4083-b388-c76e178841b7", "historyId": "2f776079b1484ad73c7cb53c60227367", "testCaseId": "193dc5b35ff0b4f40add5dddccbd028e", "fullName": "Tests.test_Sites.TestSites#test_20", "labels": [{"name": "feature", "value": "Individual Sites"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "flaky(reruns=3, reruns_delay=1)"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_Sites"}, {"name": "subSuite", "value": "TestSites"}, {"name": "host", "value": "fv-az1040-713"}, {"name": "thread", "value": "1788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_Sites"}], "links": [{"type": "tms", "url": "https://hedgehoglabqa.testrail.io/index.php?/cases/view/58413", "name": "C58413"}, {"type": "issue", "url": "https://hedgehog-lab.atlassian.net/browse/QP-356", "name": "Epic QP-356"}, {"type": "issue", "url": "https://hedgehog-lab.atlassian.net/browse/QP-264", "name": "Story QP-264"}]}