{"uuid": "49325060-adc9-4987-b348-4a3d17ddd26d", "children": ["bdb61520-fda0-4f20-8af8-069c8c327f66", "04b67cb5-f5b0-4850-b1d7-4ca59638cf29"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000\n  (Session info: MicrosoftEdge=129.0.2792.89)\nStacktrace:\n#0 0x558c9fe2a1ae <unknown>\n#1 0x558c9faed686 <unknown>\n#2 0x558c9fad6bc8 <unknown>\n#3 0x558c9fad6992 <unknown>\n#4 0x558c9fad4de4 <unknown>\n#5 0x558c9fad5254 <unknown>\n#6 0x558c9fae9c37 <unknown>\n#7 0x558c9faf989e <unknown>\n#8 0x558c9fafe9cb <unknown>\n#9 0x558c9fad5845 <unknown>\n#10 0x558c9faf9520 <unknown>\n#11 0x558c9fb81572 <unknown>\n#12 0x558c9fb62013 <unknown>\n#13 0x558c9fb3019d <unknown>\n#14 0x558c9fb30e8e <unknown>\n#15 0x558c9fdfd161 <unknown>\n#16 0x558c9fe003cd <unknown>\n#17 0x558c9fdffe4b <unknown>\n#18 0x558c9fe00835 <unknown>\n#19 0x558c9fdee7c2 <unknown>\n#20 0x558c9fe00bbd <unknown>\n#21 0x558c9fdd92b5 <unknown>\n#22 0x558c9fe1a738 <unknown>\n#23 0x558c9fe1a94d <unknown>\n#24 0x558c9fe28ff1 <unknown>\n#25 0x7f7709c94ac3 <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Common/BaseClass.py\", line 100, in driver\n    driver.maximize_window()\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 499, in maximize_window\n    self.execute(command, None)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1730604378385, "stop": 1730604721984}], "start": 1730604378385, "stop": 1730604722073}